services:
    autumn:
        image: autumn:latest
        restart: unless-stopped
        container_name: autumn
        volumes:
            - ./src:/autumn
    php:
        image: dunglas/frankenphp
        ports:
            - 8080:80
            - 443:443
        volumes:
            - ./html:/app/public
            - ./src/private:/private
            - ./caddy/data:/data
            - ./caddy/config:/config
