services:
    autumn:
        image: autumn:latest
        restart: unless-stopped
        volumes:
            - ./src:/autumn
    php:
        image: php:fpm-alpine
        restart: unless-stopped
        volumes:
            - ./html:/html
            - ./src/private:/private
        networks:
            - internal
    web:
        image: nginx:latest
        restart: unless-stopped
        ports:
            - 48080:80
        volumes:
            - ./html:/html
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - internal
networks:
    internal:
        driver: bridge
