services:
    autumn:
        image: autumn:latest
        restart: unless-stopped
        container_name: autumn
        volumes:
            - ./private:/autumn/private
    web:
        image: halloween:latest
        restart: unless-stopped
        container_name: halloween
        ports:
            - 8080:8080
        volumes:
            - ./private:/private
        environment:
            - SERVER_NAME=:8080
